/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_And_Packages;

import CLS.DB;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arjuna
 */
public class View_item_1 extends javax.swing.JPanel {
    private Component RootPanel;

    /**
     * Creates new form View_item
     */
    public View_item_1() {
        initComponents();
        loadtable();
        setcount();
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
    }
    
    String path = "";
    public static String id = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(990, 530));
        setMinimumSize(new java.awt.Dimension(990, 530));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 530));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Store items");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content bar.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Category", "Use for", "Rental Price", "Current Quantity", "All Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 760, 310));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203726_editor_list_view_hambuger_menu.png"))); // NOI18N
        jButton5.setText("More Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203462_black_2_audio_simple_repeat_2.png"))); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 280, 50));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("All item count is : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Load item count");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID Or Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 250, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 200, 230));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203980_editor_document_file_add_2.png"))); // NOI18N
        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 100, 30));

        jRadioButton1.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Item Name");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Category");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int raw = jTable1.getSelectedRowCount();
        if (raw == 1){
            id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            View_item_3 v2 = new View_item_3();
            v2.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String s  = "";
        try {
            String ss = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT image FROM inventory_item WHERE item_id = '"+ss+"'");
            while (rs.next()) {
                s  = rs.getString("image");
            }
            if (s != null){
                s = s.replace("/", "//");
                InputStream is = new FileInputStream(s);
                BufferedImage read = ImageIO.read(is);
                Image icon = read.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
                jLabel5.setIcon(new ImageIcon(icon));
                jButton2.setText("Change");
            }else{
                jLabel5.setIcon(null);
                jButton2.setText("Upload");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jLabel5.setVisible(true);
        jButton2.setVisible(true);
        if (jLabel5.getIcon() == null){
            jButton2.setText("Upload");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            int i = jFileChooser1.showOpenDialog(this);
            if (i == 0) {
                path = jFileChooser1.getSelectedFile().getPath();
                BufferedImage read = ImageIO.read(jFileChooser1.getSelectedFile());
                Image icon = read.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
                jLabel5.setIcon(new ImageIcon(icon));
                jButton2.setText("Change");
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        ResultSet rs = null;
        if (jTextField1.getText().isEmpty()){
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
        }
        try {
            if (jTextField1.getText().length() >= 5){
                String s = jTextField1.getText().substring(0, 5);
                if (s.equals("init_")){
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item WHERE item_id LIKE '"+jTextField1.getText()+"%'");
                }else{
                    jRadioButton1.setVisible(true);
                    jRadioButton2.setVisible(true);
                    if (jRadioButton2.isSelected()){
                        rs = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item WHERE category LIKE '%"+jTextField1.getText()+"%'");
                    }else{
                        rs = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item WHERE item_name LIKE '%"+jTextField1.getText()+"%'");
                    }
                }
            }else{
                jRadioButton1.setVisible(true);
                jRadioButton2.setVisible(true);
                if (jRadioButton2.isSelected()){
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item WHERE category LIKE '%"+jTextField1.getText()+"%'");
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item WHERE item_name LIKE '%"+jTextField1.getText()+"%'");
                }
            }
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("item_id"));
                v.add(rs.getString("item_name"));
                v.add(rs.getString("category"));
                v.add(rs.getString("use_for"));
                v.add(rs.getString("rental_price"));
                v.add(rs.getString("quantity"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (jTextField1.getText().isEmpty()){
            loadtable();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

        if (jTable1.getSelectedRowCount() == 0){
            jLabel5.setVisible(false);
            jButton2.setVisible(false);
        }
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (jTable1.getSelectedRowCount() != 0){
            String ss = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            if (jLabel5.getIcon() != null){
                try {
                    path = path.replace("\\", "/");
                    DB.getCon().createStatement().executeUpdate("UPDATE inventory_item set image = '"+path+"' WHERE item_id = '"+ss+"'");
                }catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged

        jTextField1.requestFocus();
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged

        jTextField1.requestFocus();
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void loadtable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        int qt1 = 0;
        int qt2 = 0;
        String id = "";
        try {
            ResultSet rs1 = null;
            ResultSet rs2 = DB.getCon().createStatement().executeQuery("SELECT * FROM inventory_item");
            while(rs2.next()){
                qt1 = rs2.getInt("quantity");
                id = rs2.getString("item_id");
                rs1 = DB.getCon().createStatement().executeQuery("SELECT event_item_qty FROM inventory_item WHERE item_id = '"+id+"'");
                while (rs1.next()) {                    
                    qt2 = rs1.getInt("event_item_qty");
                }
                qt1 = qt1 - qt2;
                Vector v = new Vector();
                v.add(id);
                v.add(rs2.getString("item_name"));
                v.add(rs2.getString("category"));
                v.add(rs2.getString("use_for"));
                v.add(rs2.getString("rental_price"));
                v.add(qt1);
                v.add(rs2.getString("quantity"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setcount() {
        jLabel2.setText( "" + jTable1.getRowCount());
    }
}
