/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Finance;

import CLS.DB;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import Reports.Reports_about_payroll;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Arjuna
 */
public class Accounts_payment extends javax.swing.JPanel {
    private Component RootPanel;

    /**
     * Creates new form Accounts_payment
     */
    
    Border brr = null;
    Border brr2 = null;
    
    public Accounts_payment() {
        initComponents();
        autogen();
        loadcombo();
        loadtable();
        
        settot();
        Date d = new Date();
        jDateChooser1.setDate(d);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton5.setSelected(false);
        jLayeredPane2.setVisible(false);
    }
    
    double tot = 0;
    int i = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1010, 510));
        setMinimumSize(new java.awt.Dimension(1010, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203980_editor_document_file_add_2.png"))); // NOI18N
        jButton3.setText("View More Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Slip No :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTable1.setBackground(new java.awt.Color(240, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slip Number", "Description", "Charge", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 120));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203781_meanicons_24.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 390, 110, -1));

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Employee Salary");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content bar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total payment Of This Month :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 330, 30));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, 30));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new small save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Employ ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print-icon.png"))); // NOI18N
        jButton6.setText("Print");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 100, 30));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 200, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Description :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Charge :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 330, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 330, 30));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 220, 30));

        jTextField10.setEditable(false);
        jTextField10.setText("Rs.");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 240, 30));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(42, 42, 205));
        jLabel11.setText("Payment Type :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 20));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(42, 42, 205));
        jRadioButton4.setText("Cash");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(42, 42, 205));
        jRadioButton5.setText("Cheque");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank info", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(42, 42, 205));
        jLabel16.setText("Bank :");
        jLabel16.setBounds(10, 80, 38, 15);
        jLayeredPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(42, 42, 205));
        jLabel17.setText("Cheque no :");
        jLabel17.setBounds(10, 40, 74, 15);
        jLayeredPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(42, 42, 205));
        jLabel18.setText("Branch :");
        jLabel18.setBounds(10, 120, 50, 15);
        jLayeredPane2.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField11.setBackground(new java.awt.Color(227, 217, 217));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(51, 51, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
        });
        jTextField11.setBounds(90, 30, 210, 30);
        jLayeredPane2.add(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField12.setBackground(new java.awt.Color(227, 217, 217));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(51, 51, 255));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.setBounds(90, 70, 210, 30);
        jLayeredPane2.add(jTextField12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField13.setBackground(new java.awt.Color(227, 217, 217));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(51, 51, 255));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.setBounds(90, 110, 210, 30);
        jLayeredPane2.add(jTextField13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 310, 160));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//        jTextField3.setText(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
//        jTextField4.setText(dtm.getValueAt(jTable1.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            if (jTable1.getRowCount() != 0){
                if (jTable1.getSelectedRowCount() != 0){
                    String ss = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                    DB.getCon().createStatement().executeUpdate("DELETE FROM pay_roll WHERE slip_no = '"+ss+"'");
                    dtm.removeRow(jTable1.getSelectedRow());
                }else{
                    String ss = jTable1.getValueAt(jTable1.getRowCount() - 1, 0).toString();
                    DB.getCon().createStatement().executeUpdate("DELETE FROM pay_roll WHERE slip_no = '"+ss+"'");
                    dtm.removeRow(jTable1.getRowCount() - 1);
                }
            }
            settot();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
//        jTextField3.requestFocus();
//        jTextField3.setText("");
//        jTextField3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int iii = 0;
        Border br = new LineBorder(Color.red);
        if (jRadioButton5.isSelected()){
            if (jTextField3.getText().isEmpty()){
                jTextField3.setBorder(br);
            iii = 1;
            }
            if (jTextField4.getText().isEmpty()){
                jTextField4.setBorder(br);
                iii = 1;
            }
            if (jDateChooser1.getDate() == null){
                jDateChooser1.setBorder(br);
                iii = 1;
            }
            if (jTextField11.getText().isEmpty()){
                jTextField11.setBorder(br);
                iii = 1;
            }
            if (jTextField12.getText().isEmpty()){
                jTextField12.setBorder(br);
                iii = 1;
            }
            if (jTextField13.getText().isEmpty()){
                jTextField13.setBorder(br);
                iii = 1;
            }
        }else{
            if (jTextField3.getText().isEmpty()){
                jTextField3.setBorder(br);
            iii = 1;
            }
            if (jTextField4.getText().isEmpty()){
                jTextField4.setBorder(br);
                iii = 1;
            }
            if (jDateChooser1.getDate() == null){
                jDateChooser1.setBorder(br);
                iii = 1;
            }
        }
        if (iii == 1){
            JOptionPane.showMessageDialog(RootPanel, "Complete These Textboxes", "Error", JOptionPane.ERROR_MESSAGE);
            jTextField3.requestFocus();
        }else{
            String type = "";
            Date d = new Date();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdf2 = new SimpleDateFormat("HH:mm:ss");
            String s1 = sdf1.format(d);
            String s2 = sdf2.format(d);
            if (jRadioButton4.isSelected()){
                type = "Cash";
                try {
                    DB.getCon().createStatement().executeUpdate("INSERT INTO pay_roll(slip_no,employee_reg_no,description,charge,payment_type,date,time,user) VALUES ('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem().toString()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+type+"','"+s1+"','"+s2+"','"+Login.User_login.user+"')");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }else{
                type = "Cheque";
                try {
                    DB.getCon().createStatement().executeUpdate("INSERT INTO pay_roll VALUES ('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem().toString()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+type+"','"+jTextField11.getText()+"','"+jTextField12.getText()+"','"+jTextField13.getText()+"','"+s1+"','"+s2+"','"+Login.User_login.user+"')");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            v.add(jTextField1.getText());
            v.add(jTextField3.getText());
            v.add(jTextField4.getText());
            v.add(s1);
            dtm.addRow(v);
            autogen();
            settot();
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField3.requestFocus();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Saved Sucessful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed

    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased

    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new Reports_about_payroll().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked

    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged

        jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked

    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged

        jLayeredPane2.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed

        jTextField12.requestFocus();
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        i+=1;
        if (i > 1){
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE reg_no = '"+jComboBox1.getSelectedItem().toString()+"'");
                while (rs.next()){
                    jTextField2.setText(rs.getString("name"));
                    if (!(rs.getString("image").isEmpty())){
                        String s  = rs.getString("image");
                        s = s.replace("/", "//");
                        InputStream is = new FileInputStream(s);
                        BufferedImage read = ImageIO.read(is);
                        Image icon = read.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
                        jLabel15.setIcon(new ImageIcon(icon));
                    }else{
                        jLabel15.setIcon(null);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            loadtable();
            jTextField3.requestFocus();
            i = 0;
        }else{
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

        brr = jTextField3.getBorder();
        brr2 = jDateChooser1.getBorder();
        jTextField3.requestFocus();
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

        jTextField4.requestFocus();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

        if (jRadioButton5.isSelected()){
            jTextField11.requestFocus();
        }else{
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained

        jDateChooser1.setBorder(brr2);
        jTextField3.setBorder(brr);
        jTextField4.setBorder(brr);
        jTextField11.setBorder(brr);
        jTextField12.setBorder(brr);
        jTextField13.setBorder(brr);
        setimage();
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained

        jDateChooser1.setBorder(brr2);
        jTextField3.setBorder(brr);
        jTextField4.setBorder(brr);
        jTextField11.setBorder(brr);
        jTextField12.setBorder(brr);
        jTextField13.setBorder(brr);
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

        int i = evt.getKeyChar();
        char c = evt.getKeyChar();
        if (!(c>= '0' & c<= '9')){
            if (i != 46){
                evt.consume();
            }
            if (i == 8){
            }else if (i == 10){
            }else if (i == 46){
            }else{
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed

        jButton1.requestFocus();
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed

        jTextField13.requestFocus();
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        Date dd = new Date();
        jDateChooser1.setMaxSelectableDate(dd);
    }//GEN-LAST:event_jDateChooser1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void loadcombo() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT reg_no FROM employee WHERE state = '"+"Not_Remove"+"'");
            while (rs.next()){
                jComboBox1.addItem(rs.getString("reg_no"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadtable() {
        if (jComboBox1.getItemCount() != 0){
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM pay_roll WHERE employee_reg_no = '"+jComboBox1.getSelectedItem().toString()+"'");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                while (rs.next()){
                    Vector v = new Vector();
                    v.add(rs.getString("slip_no"));
                    v.add(rs.getString("description"));
                    v.add(rs.getString("charge"));
                    v.add(rs.getString("date"));
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void autogen() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM pay_roll");
                if (!(rs.next())){
                    jTextField1.setText("pr_00000001");
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT MAX(slip_no) FROM pay_roll");
                    while (rs.next()){
                        String s = rs.getString("MAX(slip_no)");
                        int i = Integer.parseInt(s.substring(3, 11));
                        i+=1;
                        NumberFormat formatter = new DecimalFormat("00000000");
                        jTextField1.setText("pr_" + formatter.format(i));
                    }
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void settot() {
        tot = 0;
        int row = jTable1.getRowCount();
        int i = 0;
        if (row != 0){
            while (i < row){
                double d1 = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
                tot = tot + d1;
                i+=1;
            }
        }
        jTextField9.setText("" + tot);
    }

    private void setimage() {
        if (jComboBox1.getItemCount() != 0){
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE reg_no = '"+jComboBox1.getSelectedItem().toString()+"'");
                while (rs.next()){
                    jTextField2.setText(rs.getString("name"));
                    if (!(rs.getString("image").isEmpty())){
                        String s  = rs.getString("image");
                        s = s.replace("/", "//");
                        InputStream is = new FileInputStream(s);
                        BufferedImage read = ImageIO.read(is);
                        Image icon = read.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
                        jLabel15.setIcon(new ImageIcon(icon));
                    }else{
                        jLabel15.setIcon(null);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }
}
