/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Finance;

import Finance.Accounts_and_transactions;
import Finance.Accounts_Invoice;
import CLS.DB;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arjuna
 */
public class Recording_Invoice extends javax.swing.JPanel {

    /**
     * Creates new form Accounts_Invoice
     */
    
    double du = 0;
    double dd = 0;
    int c = 0;
    int g = 0;
    int i = 0;
    Border brr = null;
    Border brr2 = null;
    String rid = "";
    private Component RootPanel;
    public static Date d = new Date();
    public static Vector v = new Vector();
    
    
    public Recording_Invoice() {
        initComponents();
        autogen();
        loadcombo();
        if (c != 0){
            autofill();
        }
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jLayeredPane2.setVisible(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1010, 510));
        setMinimumSize(new java.awt.Dimension(1010, 510));
        setPreferredSize(new java.awt.Dimension(1010, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 510));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 510));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recording", "Event" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 120, 30));

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Recording Invoice informations");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content bar.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("This receipt amount :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Customer Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 10));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 30));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton8.setBackground(new java.awt.Color(0, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Calculator");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(130, 10, 100, 30);
        jLayeredPane1.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print-icon.png"))); // NOI18N
        jButton6.setText("Print");
        jButton6.setBounds(20, 10, 100, 30);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.setBounds(470, 10, 110, 30);
        jLayeredPane1.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203980_editor_document_file_add_2.png"))); // NOI18N
        jButton9.setText("Record");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(240, 10, 100, 30);
        jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new small save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(350, 10, 110, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 590, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Payment details :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("load date");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Invoice no :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Recording date :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Recording ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start time", "End time", "Unit price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 440, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Due Amount :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 210, 30));

        jTextField6.setEditable(false);
        jTextField6.setText("Rs.");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 230, 30));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField14FocusGained(evt);
            }
        });
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField14KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 210, 30));

        jTextField13.setEditable(false);
        jTextField13.setText("Rs.");
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 230, 30));

        jTextField7.setEditable(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 210, 30));

        jTextField8.setEditable(false);
        jTextField8.setText("Rs.");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 230, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(42, 42, 205));
        jLabel11.setText("Payment Type :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, 20));

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(42, 42, 205));
        jRadioButton4.setText("Cash");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(42, 42, 205));
        jRadioButton5.setText("Cheque");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, -1, -1));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank info", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(42, 42, 205));
        jLabel15.setText("Bank :");
        jLabel15.setBounds(10, 80, 38, 15);
        jLayeredPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(42, 42, 205));
        jLabel16.setText("Cheque no :");
        jLabel16.setBounds(10, 40, 74, 15);
        jLayeredPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(42, 42, 205));
        jLabel17.setText("Branch :");
        jLabel17.setBounds(10, 120, 50, 15);
        jLayeredPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField9.setBackground(new java.awt.Color(227, 217, 217));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(51, 51, 255));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.setBounds(90, 30, 210, 30);
        jLayeredPane2.add(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField10.setBackground(new java.awt.Color(227, 217, 217));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(51, 51, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.setBounds(90, 70, 210, 30);
        jLayeredPane2.add(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField11.setBackground(new java.awt.Color(227, 217, 217));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(51, 51, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.setBounds(90, 110, 210, 30);
        jLayeredPane2.add(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 310, 160));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 510));
    }// </editor-fold>//GEN-END:initComponents
String type;
String payment_type;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        new Reports.Reports_about_invoice().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased

    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        if (c != 0){
            autogen();
            autofill();
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
       // jTextField3.requestFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Calculator.Cal().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked

    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      //  DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
       // jTextField3.setText(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
       // jTextField4.setText(dtm.getValueAt(jTable1.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        i+=1;
        if (i > 1){
            if (jComboBox2.getSelectedItem().equals("Event")){
                Accounts_and_transactions.jPanel1.removeAll();
                GroupLayout layout = new GroupLayout(Accounts_and_transactions.jPanel1);
                Accounts_and_transactions.jPanel1.setLayout(layout);
                Accounts_Invoice RIA = new Accounts_Invoice();
                layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(RIA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(RIA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            }else{
                Accounts_and_transactions.jPanel1.removeAll();
                GroupLayout layout = new GroupLayout(Accounts_and_transactions.jPanel1);
                Accounts_and_transactions.jPanel1.setLayout(layout);
                Recording_Invoice RI = new Recording_Invoice();
                layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(RI, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(RI, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            }
            i = 0;
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange

    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed

    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked

    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged

        jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked

    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged

        jLayeredPane2.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed

        jTextField10.requestFocus();
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jComboBox1.getItemCount() == 0){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Can Not Save This Invoice", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int iii = 0;
            Border br = new LineBorder(Color.red);
            if (jRadioButton5.isSelected()){
                if (jTextField9.getText().isEmpty()){
                jTextField9.setBorder(br);
                iii = 1;
                }
                if (jTextField10.getText().isEmpty()){
                    jTextField10.setBorder(br);
                    iii = 1;
                }
                if (jTextField11.getText().isEmpty()){
                    jTextField11.setBorder(br);
                    iii = 1;
                }
            }
            if ((jDateChooser1.getDate() == null)){
                jDateChooser1.setBorder(br);
                iii = 1;
            }
            if (jTextField14.getText().isEmpty()){
                jTextField14.setBorder(br);
                iii = 1;
            }
            if (iii == 1){
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(RootPanel, "Complete These Textboxes", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField14.requestFocus();
            }else{
                Date d = new Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat sdf2 = new SimpleDateFormat("HH:mm:ss");
                String s1 = sdf1.format(d);
                String s2 = sdf2.format(d);
                String type = "";
                try {
                    ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT invoice_no FROM recording_invoice WHERE invoice_no = '"+jTextField1.getText()+"'");
                        if(!rs.next()){
                            if (jRadioButton4.isSelected()){
                                type = "Cash";
                                try {
                                    DB.getCon().createStatement().executeUpdate("INSERT INTO recording_invoice(invoice_no,recording_song_info_recording_id,recording_customer_reg_no,date,time,total_amount,this_receipt_amount,due_amount,payment_type,user) VALUES ('"+jTextField1.getText()+"', '"+jComboBox1.getSelectedItem()+"', '"+rid+"', '"+s1+"','"+s2+"', '"+jTextField5.getText()+"', '"+jTextField14.getText()+"', '"+jTextField7.getText()+"', '"+type+"', '"+Login.User_login.user+"')");
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }else{
                                type = "Cheque";
                                try {
                                    DB.getCon().createStatement().executeUpdate("INSERT INTO recording_invoice VALUES ('"+jTextField1.getText()+"', '"+jComboBox1.getSelectedItem()+"', '"+rid+"', '"+s1+"','"+s2+"', '"+jTextField5.getText()+"', '"+jTextField14.getText()+"', '"+jTextField7.getText()+"', '"+type+"', '"+jTextField9.getText()+"', '"+jTextField10.getText()+"', '"+jTextField11.getText()+"', '"+Login.User_login.user+"')");
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
                        }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(RootPanel, "Saved Sucessful");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        jTextField8.setText("");
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange

    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

        brr = jTextField14.getBorder();
        brr2 = jDateChooser1.getBorder();
        jTextField14.requestFocus();
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed

        jTextField11.requestFocus();
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed

        jButton2.requestFocus();
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        Date dd = new Date();
        jDateChooser1.setMaxSelectableDate(dd);
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped

    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased

        String ss = "";
        try {   
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT DISTINCT due_amount FROM recording_invoice WHERE recording_song_info_recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
            if (rs.next()){
                rs = DB.getCon().createStatement().executeQuery("SELECT DISTINCT due_amount FROM recording_invoice WHERE recording_song_info_recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
                while (rs.next()) {                
                    du = Double.parseDouble(rs.getString("due_amount"));     
                    ss = rs.getString("due_amount");
                }
            }else{
                du = Double.parseDouble(jTextField5.getText());
                ss = jTextField5.getText();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        int i = evt.getKeyChar();
        if (i >= 48 & i <= 57){
            dd = Double.parseDouble(jTextField14.getText());
            jTextField7.setText("" + (du - dd));
            double d = Double.parseDouble(jTextField7.getText());
            if (du < dd){
                Toolkit.getDefaultToolkit().beep();
                int ii = ss.length();
                String s = jTextField14.getText().substring(0, ii - 3);
                dd = Double.parseDouble(s);
                jTextField14.setText(s);
                jTextField7.setText("" + (du - dd));
            }
        }else{
            if (i == 8 || i == 10 || i == 46 || i == 127){
                if (jTextField14.getText().isEmpty()){
                    jTextField7.setText("" + du);
                }else{
                    dd = Double.parseDouble(jTextField14.getText());
                    jTextField7.setText("" + (du - dd));
                }
            }else{
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_jTextField14KeyReleased

    private void jTextField14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyPressed

    }//GEN-LAST:event_jTextField14KeyPressed

    private void jTextField14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusGained

        jDateChooser1.setBorder(brr2);
        jTextField14.setBorder(brr);
        jTextField9.setBorder(brr);
        jTextField10.setBorder(brr);
        jTextField11.setBorder(brr);
    }//GEN-LAST:event_jTextField14FocusGained

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed

        if (jRadioButton5.isSelected()){
            jTextField9.requestFocus();
        }else{
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jTextField14ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void autogen() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM recording_invoice");
                if (!(rs.next())){
                    jTextField1.setText("rein_00000001");
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT MAX(invoice_no) FROM recording_invoice");
                    while (rs.next()){
                        String s = rs.getString("MAX(invoice_no)");
                        int i = Integer.parseInt(s.substring(5, 13));
                        i+=1;
                        NumberFormat formatter = new DecimalFormat("00000000");
                        jTextField1.setText("rein_" + formatter.format(i));
                    }
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void autofill() {
        autogen();
        Date d = new Date();
        double d2 = 0;
        jDateChooser1.setDate(d);
        String reg = "";
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM recording_song_info WHERE recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
            while (rs.next()){
                jLabel12.setText(rs.getString("date"));
                reg = rs.getString("recording_customer_reg_no");
            }
            rs = DB.getCon().createStatement().executeQuery("SELECT name FROM recording_customer WHERE reg_no = '"+reg+"'");
            while(rs.next()){
                jTextField2.setText(rs.getString("name"));
                rid = reg;
            }
            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM recording_song_info WHERE recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("start_time"));
                v.add(rs.getString("end_time"));
                v.add(rs.getString("unit_prise"));
                dtm.addRow(v);
            }
            rs = DB.getCon().createStatement().executeQuery("SELECT DISTINCT due_amount FROM recording_invoice WHERE recording_song_info_recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
            if (rs.first()){
                rs = DB.getCon().createStatement().executeQuery("SELECT DISTINCT due_amount FROM recording_invoice WHERE recording_song_info_recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
                while (rs.next()){
                    du = Double.parseDouble(rs.getString("due_amount"));
                    jTextField7.setText("" + du);
                }
            }else{
                rs = DB.getCon().createStatement().executeQuery("SELECT total_amount FROM recording_song_info WHERE recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
                while (rs.next()) {                    
                    jTextField5.setText(rs.getString("total_amount"));
                }
                du = Double.parseDouble(jTextField5.getText());
                jTextField7.setText("" + du);
            }
            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM recording_song_info WHERE recording_id = '"+jComboBox1.getSelectedItem().toString()+"'");
            while (rs.next()) {                    
                jTextField5.setText(rs.getString("total_amount"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextField8.requestFocus();
    }

    private void loadcombo() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT recording_id FROM recording_song_info");
            while (rs.next()){
                jComboBox1.addItem(rs.getString("recording_id"));
            }
            rs = DB.getCon().createStatement().executeQuery("SELECT DISTINCT recording_song_info_recording_id FROM recording_invoice WHERE due_amount = 0.0");
            while (rs.next()){
                jComboBox1.removeItem(rs.getString("recording_song_info_recording_id"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        c = jComboBox1.getItemCount();
    }
}
