/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Menu;

import Settings.Account_settings;
import Event.Deal;
import Finance.Accounts_and_transactions;
import AppPackage.AnimationClass;

import CLS.DB;
import Employee.Main;
import Inventory_And_Packages.Inventory_menu;
import java.awt.Toolkit;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import nickyb.sqleonardo.querybuilder.BasePanel;
import Notes.Write_notes;
import Mail.Send_mail;
import Recordings.Rec_main;


import Calculator.Cal;
import Settings.Main_fram;


/**
 *
 * @author Arjuna
 */
public class Main_menu extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    private Accounts_and_transactions inventory_menu;

    /**
     * Creates new form main_sample
     */
    public Main_menu() {
        initComponents();
        showTime();
        showDate();
        load_event_calender();
        removepanel();
    }
    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss: a");
                String s = sdf.format(d);
                Time.setText(s);
            }
        }).start();
    }
    void showDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String s = sdf.format(d);
        Date.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArrowRight = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        calculator = new javax.swing.JLabel();
        notes = new javax.swing.JLabel();
        slider = new javax.swing.JLabel();
        ArrowLeft = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        settings_buttons = new javax.swing.JLabel();
        home_button = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Header_text = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        footer_bar = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        move = new javax.swing.JLabel();
        accounts = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        header_bar = new javax.swing.JLabel();
        deal = new javax.swing.JLabel();
        radisiz_group = new javax.swing.JLabel();
        recording = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 727));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ArrowRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/right.png"))); // NOI18N
        ArrowRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ArrowRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ArrowRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ArrowRightMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ArrowRightMouseReleased(evt);
            }
        });
        getContentPane().add(ArrowRight);
        ArrowRight.setBounds(1380, 60, 50, 40);

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(1380, 140, 90, 70);

        calculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calc.png"))); // NOI18N
        calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculatorMouseExited(evt);
            }
        });
        getContentPane().add(calculator);
        calculator.setBounds(1380, 270, 90, 70);

        notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notes.png"))); // NOI18N
        notes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notesMouseExited(evt);
            }
        });
        getContentPane().add(notes);
        notes.setBounds(1380, 400, 90, 70);

        slider.setBackground(new java.awt.Color(102, 204, 255));
        slider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/slide bar.png"))); // NOI18N
        getContentPane().add(slider);
        slider.setBounds(1370, 50, 120, 650);

        ArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left.png"))); // NOI18N
        ArrowLeft.setToolTipText("View tools");
        ArrowLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArrowLeftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ArrowLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ArrowLeftMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ArrowLeftMouseReleased(evt);
            }
        });
        getContentPane().add(ArrowLeft);
        ArrowLeft.setBounds(1320, 60, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout - Copy.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1160, 60, 120, 40);

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));
        jPanel1.setMaximumSize(new java.awt.Dimension(1180, 570));
        jPanel1.setMinimumSize(new java.awt.Dimension(1180, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 120, 1180, 570);

        settings_buttons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account settings.png"))); // NOI18N
        settings_buttons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings_buttons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_buttonsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settings_buttonsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settings_buttonsMouseExited(evt);
            }
        });
        getContentPane().add(settings_buttons);
        settings_buttons.setBounds(990, 70, 150, 30);

        home_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        home_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_buttonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home_buttonMouseReleased(evt);
            }
        });
        getContentPane().add(home_button);
        home_button.setBounds(860, 70, 110, 30);

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel3.setText("User");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 70, 60, 30);

        jLabel5.setText("About Us");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 700, 100, 24);

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 70, 220, 30);

        Header_text.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Header_text.setForeground(new java.awt.Color(240, 240, 240));
        Header_text.setText("Event Management Application");
        getContentPane().add(Header_text);
        Header_text.setBounds(610, 0, 218, 19);

        Date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(240, 19, 26));
        Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date.setText("Date");
        getContentPane().add(Date);
        Date.setBounds(1080, 700, 110, 20);

        Time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(240, 19, 26));
        Time.setText("time");
        getContentPane().add(Time);
        Time.setBounds(1240, 700, 120, 20);

        footer_bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/footer.png"))); // NOI18N
        getContentPane().add(footer_bar);
        footer_bar.setBounds(0, 700, 1366, 30);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(1270, 0, 40, 40);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(1320, 0, 50, 40);

        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        getContentPane().add(move);
        move.setBounds(0, 0, 1370, 40);

        accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accounts.png"))); // NOI18N
        accounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountsMouseExited(evt);
            }
        });
        getContentPane().add(accounts);
        accounts.setBounds(0, 230, 160, 70);

        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventory.png"))); // NOI18N
        inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryMouseExited(evt);
            }
        });
        getContentPane().add(inventory);
        inventory.setBounds(0, 310, 160, 80);

        header_bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header.png"))); // NOI18N
        getContentPane().add(header_bar);
        header_bar.setBounds(0, 0, 1366, 120);

        deal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Deal.png"))); // NOI18N
        deal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dealMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dealMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dealMouseReleased(evt);
            }
        });
        getContentPane().add(deal);
        deal.setBounds(0, 140, 160, 80);

        radisiz_group.setBackground(new java.awt.Color(255, 255, 255));
        radisiz_group.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radisiz_group.setForeground(new java.awt.Color(255, 255, 255));
        radisiz_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/radisiz group.png"))); // NOI18N
        radisiz_group.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radisiz_group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radisiz_groupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radisiz_groupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radisiz_groupMouseExited(evt);
            }
        });
        getContentPane().add(radisiz_group);
        radisiz_group.setBounds(0, 480, 160, 70);

        recording.setBackground(new java.awt.Color(255, 255, 255));
        recording.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recording.setForeground(new java.awt.Color(255, 255, 255));
        recording.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recording.png"))); // NOI18N
        recording.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recording.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordingMouseExited(evt);
            }
        });
        getContentPane().add(recording);
        recording.setBounds(0, 400, 160, 70);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 720);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 720);

        setBounds(0, 0, 1368, 727);
    }// </editor-fold>//GEN-END:initComponents

    private void dealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/img/Deal glow.png"));
        deal.setIcon(ii);
    }//GEN-LAST:event_dealMouseEntered

    private void dealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealMouseExited
         ImageIcon ii1 = new ImageIcon(getClass().getResource("/img/Deal.png"));
        deal.setIcon(ii1);
    }//GEN-LAST:event_dealMouseExited

    private void accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseEntered
         ImageIcon ii2 = new ImageIcon(getClass().getResource("/img/accounts glow.png"));
        accounts.setIcon(ii2);
    }//GEN-LAST:event_accountsMouseEntered

    private void accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseExited
         ImageIcon ii3 = new ImageIcon(getClass().getResource("/img/accounts.png"));
        accounts.setIcon(ii3);
    }//GEN-LAST:event_accountsMouseExited

    private void inventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseEntered
        ImageIcon ii4 = new ImageIcon(getClass().getResource("/img/inventory glow.png"));
        inventory.setIcon(ii4);
    }//GEN-LAST:event_inventoryMouseEntered

    private void inventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseExited
        ImageIcon ii5 = new ImageIcon(getClass().getResource("/img/inventory.png"));
        inventory.setIcon(ii5);
    }//GEN-LAST:event_inventoryMouseExited

    private void dealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealMouseClicked
        jPanel1.removeAll();
        GroupLayout gl=new GroupLayout(jPanel1);
       
        
        jPanel1.setLayout(gl);
        Deal deal=new Deal();
        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(deal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(deal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    
    }//GEN-LAST:event_dealMouseClicked

    private void dealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealMousePressed
        
    }//GEN-LAST:event_dealMousePressed

    private void dealMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealMouseReleased
        
    }//GEN-LAST:event_dealMouseReleased

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        ImageIcon iii = new ImageIcon(getClass().getResource("/img/minimize2.png"));
        minimize.setIcon(iii);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        ImageIcon iii = new ImageIcon(getClass().getResource("/img/minimize.png"));
        minimize.setIcon(iii);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        this.setState(Main_menu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        try {
            Toolkit.getDefaultToolkit().beep();
            int ii= JOptionPane.showConfirmDialog(rootPane, "Do you want to exit ?", "Exit", JOptionPane.WARNING_MESSAGE);

            if (ii==0) {

                System.exit(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/img/close2.png"));
        close.setIcon(i);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon i1 = new ImageIcon(getClass().getResource("/img/close.png"));
        close.setIcon(i1);
    }//GEN-LAST:event_closeMouseExited

    private void accountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseClicked
jPanel1.removeAll();
        GroupLayout gl1=new GroupLayout(jPanel1);
       
        
        jPanel1.setLayout(gl1);
        Accounts_and_transactions Accounts_and_transactions=new Accounts_and_transactions();
        gl1.setHorizontalGroup(gl1.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(Accounts_and_transactions, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl1.setVerticalGroup(gl1.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(Accounts_and_transactions, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                // TODO add your handling code here:
    }//GEN-LAST:event_accountsMouseClicked

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked

         jPanel1.removeAll();
        GroupLayout gl2=new GroupLayout(jPanel1);

        jPanel1.setLayout(gl2);
        Inventory_And_Packages.Inventory_menu is = new Inventory_menu();
        gl2.setHorizontalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( is, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl2.setVerticalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( is, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    }//GEN-LAST:event_inventoryMouseClicked

    private void recordingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordingMouseClicked

        jPanel1.removeAll();
        GroupLayout gl4=new GroupLayout(jPanel1);

        jPanel1.setLayout(gl4);
         Rec_main recording_menu = new Rec_main();
        gl4.setHorizontalGroup(gl4.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( recording_menu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl4.setVerticalGroup(gl4.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( recording_menu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    }//GEN-LAST:event_recordingMouseClicked

    private void radisiz_groupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radisiz_groupMouseClicked
        jPanel1.removeAll();
        GroupLayout group=new GroupLayout(jPanel1);

        jPanel1.setLayout(group);        
        Employee.Main emp = new Main();
        group.setHorizontalGroup(group.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( emp, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        group.setVerticalGroup(group.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( emp, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    }//GEN-LAST:event_radisiz_groupMouseClicked

    private void radisiz_groupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radisiz_groupMouseEntered
        ImageIcon rg = new ImageIcon(getClass().getResource("/img/radisiz group glow.png"));
        radisiz_group.setIcon(rg);
    }//GEN-LAST:event_radisiz_groupMouseEntered

    private void radisiz_groupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radisiz_groupMouseExited
         ImageIcon rgg = new ImageIcon(getClass().getResource("/img/radisiz group.png"));
        radisiz_group.setIcon(rgg);
    }//GEN-LAST:event_radisiz_groupMouseExited

    private void recordingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordingMouseEntered
         ImageIcon rec = new ImageIcon(getClass().getResource("/img/recording glow.png"));
        recording.setIcon(rec);
    }//GEN-LAST:event_recordingMouseEntered

    private void recordingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordingMouseExited
        ImageIcon recc = new ImageIcon(getClass().getResource("/img/recording.png"));
        recording.setIcon(recc);
    }//GEN-LAST:event_recordingMouseExited

    private void home_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseEntered
        ImageIcon h = new ImageIcon(getClass().getResource("/img/Home button glow.png"));
        home_button.setIcon(h);
    }//GEN-LAST:event_home_buttonMouseEntered

    private void home_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseExited
        ImageIcon hbg = new ImageIcon(getClass().getResource("/img/home.png"));
        home_button.setIcon(hbg);
    }//GEN-LAST:event_home_buttonMouseExited

    private void settings_buttonsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_buttonsMouseEntered
        ImageIcon sb = new ImageIcon(getClass().getResource("/img/account settings glow.png"));
        settings_buttons.setIcon(sb);
    }//GEN-LAST:event_settings_buttonsMouseEntered

    private void settings_buttonsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_buttonsMouseExited
        ImageIcon sbg = new ImageIcon(getClass().getResource("/img/account settings.png"));
        settings_buttons.setIcon(sbg);
    }//GEN-LAST:event_settings_buttonsMouseExited

    private void settings_buttonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_buttonsMouseClicked
        new Settings.Main_fram().setVisible(true);
    }//GEN-LAST:event_settings_buttonsMouseClicked

    private void home_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseReleased

        load_event_calender();
    }//GEN-LAST:event_home_buttonMouseReleased

    private void ArrowLeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowLeftMouseReleased
       
        
//         ImageIcon iiii = new ImageIcon(getClass().getResource("/img/right.png"));
//        Arrow1.setIcon(iiii);
    }//GEN-LAST:event_ArrowLeftMouseReleased

    private void ArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowLeftMouseClicked
       
        
         AnimationClass AC= new AnimationClass();
        AC.jLabelXLeft(1370, 1250, 10, 5, slider);
        AC.jLabelXRight(1250, 1370, 10, 5, slider);
        
       // AC.jLabelXLeft(1320, 1200, 8, 5, Arrow1);
       // AC.jLabelXRight(1200, 1320, 8, 5, Arrow1);
        
        AC.jLabelXLeft(1380, 1270, 20, 5, email);
        AC.jLabelXRight(1270, 1380, 8, 10, email);
        
        AC.jLabelXLeft(1380, 1270, 15, 5, calculator);
        AC.jLabelXRight(1270, 1380, 3, 9, calculator);
        
        AC.jLabelXLeft(1380, 1270, 10, 5, notes);
        AC.jLabelXRight(1270, 1380, 2, 8, notes);
        
        AC.jLabelXLeft(1380, 1250, 10, 5, ArrowRight);
        AC.jLabelXRight(1250, 1380, 10, 5, ArrowRight);
    }//GEN-LAST:event_ArrowLeftMouseClicked

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        ImageIcon o = new ImageIcon(getClass().getResource("/img/email glow.png"));
        email.setIcon(o);
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        ImageIcon oh = new ImageIcon(getClass().getResource("/img/email.png"));
        email.setIcon(oh);
    }//GEN-LAST:event_emailMouseExited

    private void calculatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseEntered
        ImageIcon ohh = new ImageIcon(getClass().getResource("/img/calc glow.png"));
        calculator.setIcon(ohh);
    }//GEN-LAST:event_calculatorMouseEntered

    private void calculatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseExited
        ImageIcon ohh = new ImageIcon(getClass().getResource("/img/calc.png"));
        calculator.setIcon(ohh);
    }//GEN-LAST:event_calculatorMouseExited

    private void notesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesMouseEntered
        ImageIcon ohhm = new ImageIcon(getClass().getResource("/img/notes glow.png"));
        notes.setIcon(ohhm);
    }//GEN-LAST:event_notesMouseEntered

    private void notesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesMouseExited
         ImageIcon ohhm = new ImageIcon(getClass().getResource("/img/notes.png"));
        notes.setIcon(ohhm);
    }//GEN-LAST:event_notesMouseExited

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void ArrowRightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowRightMouseReleased
         AnimationClass AC= new AnimationClass();
        //AC.jLabelXLeft(1370, 1250, 10, 5, slider);
        AC.jLabelXRight(1250, 1370, 18, 5, slider);
        
       // AC.jLabelXLeft(1320, 1200, 8, 5, Arrow1);
       // AC.jLabelXRight(1200, 1320, 8, 5, Arrow1);
        
       // AC.jLabelXLeft(1380, 1270, 20, 5, email);
        AC.jLabelXRight(1270, 1380, 20, 2, email);
        
       // AC.jLabelXLeft(1380, 1270, 15, 5, calculator);
        AC.jLabelXRight(1270, 1380, 15, 2, calculator);
        
        //AC.jLabelXLeft(1380, 1270, 10, 5, notes);
        AC.jLabelXRight(1270, 1380, 10, 2, notes);
        
       // AC.jLabelXLeft(1380, 1250, 10, 5, ArrowRight);
        AC.jLabelXRight(1250, 1380, 5, 10, ArrowRight);
    }//GEN-LAST:event_ArrowRightMouseReleased

    private void ArrowLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowLeftMouseEntered
        ImageIcon a = new ImageIcon(getClass().getResource("/img/left glow.png"));
        ArrowLeft.setIcon(a);
    }//GEN-LAST:event_ArrowLeftMouseEntered

    private void ArrowLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowLeftMouseExited
        ImageIcon aa = new ImageIcon(getClass().getResource("/img/left.png"));
        ArrowLeft.setIcon(aa);
    }//GEN-LAST:event_ArrowLeftMouseExited

    private void ArrowRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowRightMouseEntered
        ImageIcon arr = new ImageIcon(getClass().getResource("/img/right glow.png"));
        ArrowRight.setIcon(arr);
    }//GEN-LAST:event_ArrowRightMouseEntered

    private void ArrowRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowRightMouseExited
        ImageIcon arri = new ImageIcon(getClass().getResource("/img/right.png"));
        ArrowRight.setIcon(arri);
    }//GEN-LAST:event_ArrowRightMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AnimationClass AC= new AnimationClass();
        //AC.jLabelXLeft(1370, 1250, 10, 5, slider);
        AC.jLabelXRight(1250, 1370, 18, 5, slider);
        
       // AC.jLabelXLeft(1320, 1200, 8, 5, Arrow1);
       // AC.jLabelXRight(1200, 1320, 8, 5, Arrow1);
        
       // AC.jLabelXLeft(1380, 1270, 20, 5, email);
        AC.jLabelXRight(1270, 1380, 20, 2, email);
        
       // AC.jLabelXLeft(1380, 1270, 15, 5, calculator);
        AC.jLabelXRight(1270, 1380, 15, 2, calculator);
        
        //AC.jLabelXLeft(1380, 1270, 10, 5, notes);
        AC.jLabelXRight(1270, 1380, 10, 2, notes);
        
       // AC.jLabelXLeft(1380, 1250, 10, 5, ArrowRight);
        AC.jLabelXRight(1250, 1380, 5, 10, ArrowRight);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void notesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesMouseClicked
        new Write_notes().setVisible(true);
        
    }//GEN-LAST:event_notesMouseClicked

    private void calculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseClicked
        
        new Calculator.Cal().setVisible(true);
    }//GEN-LAST:event_calculatorMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT username FROM login");
            if (!(rs.next())){
                new Main_fram().setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jLabel4.setText(Login.User_login.user);
        if (jLabel4.getText() == null){
            jLabel3.setVisible(false);
        }else{
            jLabel3.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked

        new Send_mail().setVisible(true);
    }//GEN-LAST:event_emailMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        new Login.User_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        ImageIcon sb = new ImageIcon(getClass().getResource("/img/logout glow - Copy.png"));
       jLabel2.setIcon(sb);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited

        ImageIcon sbg = new ImageIcon(getClass().getResource("/img/logout - Copy.png"));
        jLabel2.setIcon(sbg);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        new About_Us.About_us().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArrowLeft;
    private javax.swing.JLabel ArrowRight;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Header_text;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel accounts;
    private javax.swing.JLabel background;
    private javax.swing.JLabel calculator;
    private javax.swing.JLabel close;
    private javax.swing.JLabel deal;
    private javax.swing.JLabel email;
    private javax.swing.JLabel footer_bar;
    private javax.swing.JLabel header_bar;
    private javax.swing.JLabel home_button;
    private javax.swing.JLabel inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel move;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel radisiz_group;
    private javax.swing.JLabel recording;
    private javax.swing.JLabel settings_buttons;
    private javax.swing.JLabel slider;
    // End of variables declaration//GEN-END:variables

    private void removepanel() {
        jPanel1.removeAll();
    }

    private void load_event_calender() {
        jPanel1.removeAll();
        GroupLayout gl=new GroupLayout(jPanel1);
        jPanel1.setLayout(gl);
        Event_calender evc = new Event_calender();
        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(evc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(evc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }

    private void crate_Account() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM login");
            if (!rs.next()){
                Account_settings ac = new Account_settings();
                ac.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
