/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import CLS.DB;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.io.FileDescriptor;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;



/**
 *
 * @author Administrator
 */
public class Reports_about_payroll extends javax.swing.JFrame {

    /**
     * Creates new form Reports_about_invoice
     */
    
    String is = null;
    String s = null;
    Map mm = new HashMap();
    String d1 = "";
    String d2 = "";
    ResultSet rs = null;
    Border br1 = null;
    int ii = 0;
    private Component RootPanel;
    
    public Reports_about_payroll() {
        initComponents();
        setlocation();
        loadcombo();
        load();
        valid();
        jComboBox2.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports About Other Expense");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Total Debit of This Report Rs :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setText("Rs.");
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 230, 30));

        jLabel1.setFont(new java.awt.Font("FrankRuehl", 1, 20)); // NOI18N
        jLabel1.setText("Reports about payrolls");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 740, 500));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 70, 30));

        jButton6.setText("Print");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 70, 30));

        jButton8.setText("Send as email");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 110, 30));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 30, 170, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Date Range", "All" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 60, 120, -1));

        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, -1));

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Employee Id Or Slip Number");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 60, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed

    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int ii = 0;
        Border brr = new LineBorder(Color.red);
        if (jComboBox2.getSelectedIndex() == 0){
            if (jDateChooser1.getDate() == null){
                jDateChooser1.setBorder(brr);
                ii = 1;
            }
        }
        if (jComboBox2.getSelectedIndex() == 1){
            if (jDateChooser1.getDate() == null){
                jDateChooser1.setBorder(brr);
                ii = 1;
            }
            if (jDateChooser2.getDate() == null){
                jDateChooser2.setBorder(brr);
                ii = 1;
            }
        }
        if (ii == 1){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Fill These Fields", "Error", JOptionPane.ERROR_MESSAGE);
            jDateChooser1.setBorder(br1);
            jDateChooser2.setBorder(br1);
        }else{
            search();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        Date d = new Date();
        if (jComboBox2.getSelectedIndex() == 1){
            jDateChooser1.setEnabled(true);
            jDateChooser2.setEnabled(true);
            jDateChooser1.setDate(d);
        }else if (jComboBox2.getSelectedIndex() == 2){
            jDateChooser1.setEnabled(false);
            jDateChooser2.setEnabled(false);
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);
        }else{
            jDateChooser1.setEnabled(true);
            jDateChooser2.setEnabled(false);
            jDateChooser1.setDate(d);
            jDateChooser2.setDate(null);
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        br1 = jDateChooser1.getBorder();
    }//GEN-LAST:event_formWindowActivated

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked

        jTextField2.setText("");
        jTextField2.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost

        if (jTextField2.getText().isEmpty()){
            jTextField2.setForeground(Color.lightGray);
            jTextField2.setText("Employee ID Or Slip Number");
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange

        jDateChooser2.setMinSelectableDate(jDateChooser1.getDate());
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports_about_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports_about_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports_about_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports_about_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports_about_payroll().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void debit() {
        double total = 0;
        try {
            while (rs.next()){
                int i = rs.getInt("charge");
                total = total + i;
            }
            jTextField5.setText("" + total);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setlocation() {
        int fheight = this.getHeight();
        int fwidth = this.getWidth();
        
        int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        int width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        
        width = ((width - fwidth) / 2);
        height = ((height - fheight) / 4);
        
        setLocation(width, height);
    }

    private void search() {
        try {
            getfile();
            InputStream iss = new FileInputStream(is);
            JasperReport jr = JasperCompileManager.compileReport(iss);
            JasperPrint jp = JasperFillManager.fillReport(jr, mm, DB.getCon());
            JRViewer jrv = new JRViewer(jp);
            if (jTabbedPane1.getTabCount() == 1){
                jTabbedPane1.removeAll();
            }
            jTabbedPane1.add("Payroll", jrv);
            debit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadcombo() {
        jComboBox1.addItem("All");
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT username FROM login");
            while (rs.next()){
                jComboBox1.addItem(rs.getString("username").toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void mindate() {
        try {
            Date d = null;
            Date dd = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT MIN(date) FROM pay_roll");
            while (rs.next()){
                d = rs.getDate("MIN(date)");
            }
            d1 = sdf.format(d);
            d2 = sdf.format(dd);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getfile() {
        getid();
        mindate();
        try {
            if (jComboBox2.getSelectedIndex() == 2){
                if (jComboBox1.getSelectedItem().toString().equals("All")){
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//All//Payments All 1.jrxml";
                        mm.put("st date" , d1);
                        mm.put("end date" , d2);
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//All//Payments All 2.jrxml";
                            mm.put("st date" , d1);
                            mm.put("end date" , d2);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND slip_no = '"+jTextField2.getText()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//All//Payments All 3.jrxml";
                            mm.put("st date" , d1);
                            mm.put("end date" , d2);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND employee_reg_no = '"+jTextField2.getText()+"'");
                        }
                    }
                }else{
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//All//Payments All 4.jrxml";
                        mm.put("st date" , d1);
                        mm.put("end date" , d2);
                        mm.put("user" , jComboBox1.getSelectedItem().toString());
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//All//Payments All 5.jrxml";
                            mm.put("st date" , d1);
                            mm.put("end date" , d2);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND slip_no = '"+jTextField2.getText()+"' And user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//All//Payments All 6.jrxml";
                            mm.put("st date" , d1);
                            mm.put("end date" , d2);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND employee_reg_no = '"+jTextField2.getText()+"' And user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }
                    }
                }
            }else if (jComboBox2.getSelectedIndex() == 0){
                Date d = jDateChooser1.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                d1 = sdf.format(d);
                if (jComboBox1.getSelectedItem().toString().equals("All")){
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 1.jrxml";
                        mm.put("date" , d1);
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 2.jrxml";
                            mm.put("date" , d1);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"' And slip_no = '"+jTextField2.getText()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 3.jrxml";
                            mm.put("date" , d1);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"' And employee_reg_no = '"+jTextField2.getText()+"'");
                        }
                    }
                }else{
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 4.jrxml";
                        mm.put("date" , d1);
                        mm.put("user" , jComboBox1.getSelectedItem().toString());
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"' And user = '"+jComboBox1.getSelectedItem().toString()+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 5.jrxml";
                            mm.put("date" , d1);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"' AND slip_no = '"+jTextField2.getText()+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//Daily//Payments Daily 6.jrxml";
                            mm.put("date" , d1);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date = '"+d1+"' AND employee_reg_no = '"+jTextField2.getText()+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }
                    }
                }
            }else if (jComboBox2.getSelectedIndex() == 1){
                Date d = jDateChooser1.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                d1 = sdf.format(d);
                d = jDateChooser2.getDate();
                d2 = sdf.format(d);
                if (jComboBox1.getSelectedItem().toString().equals("All")){
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 1.jrxml";
                        mm.put("fdate" , d1);
                        mm.put("ldate" , d2);
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 2.jrxml";
                            mm.put("fdate" , d1);
                            mm.put("ldate" , d2);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND slip_no = '"+jTextField2.getText()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 3.jrxml";
                            mm.put("fdate" , d1);
                            mm.put("ldate" , d2);
                            mm.put("id" , jTextField2.getText());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND employee_reg_no = '"+jTextField2.getText()+"'");
                        }
                    }
                }else{
                    if (jTextField2.getText().isEmpty() || jTextField2.getText().equals("Employee Id Or Slip Number")){
                        is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 4.jrxml";
                        mm.put("fdate" , d1);
                        mm.put("ldate" , d2);
                        mm.put("user" , jComboBox1.getSelectedItem().toString());
                        rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                    }else{
                        if (s.equals("pr_")){
                            is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 5.jrxml";
                            mm.put("fdate" , d1);
                            mm.put("ldate" , d2);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND slip_no = '"+jTextField2.getText()+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }else if (s.equals("em_")){
                            is = "D://Final Final Viva//Rreports//Payments//Date Range//Payments Date Range 6.jrxml";
                            mm.put("fdate" , d1);
                            mm.put("ldate" , d2);
                            mm.put("id" , jTextField2.getText());
                            mm.put("user" , jComboBox1.getSelectedItem().toString());
                            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"' AND employee_reg_no = '"+jTextField2.getText()+"' AND user = '"+jComboBox1.getSelectedItem().toString()+"'");
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void load() {
        try {
            mindate();
            is = "D://Final Final Viva//Rreports//Payments//All//Payments All 1.jrxml";
            mm.put("st date" , d1);
            mm.put("end date" , d2);
            rs = DB.getCon().createStatement().executeQuery("SELECT charge FROM pay_roll WHERE date >= '"+d1+"' AND date <= '"+d2+"'");
            InputStream iss = new FileInputStream(is);
            JasperReport jr = JasperCompileManager.compileReport(iss);
            JasperPrint jp = JasperFillManager.fillReport(jr, mm, DB.getCon());
            JRViewer jrv = new JRViewer(jp);
            if (jTabbedPane1.getTabCount() == 1){
                jTabbedPane1.removeAll();
            }
            jTabbedPane1.add("Payroll", jrv);
            debit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void valid() {
        String s = jTextField2.getText();
        if (s.length() > 2){
            s = s.substring(0, 3);
            if (s.equals("pr_")){
                if (jTextField2.getText().length() != 11){
                    ii = 1;
                }
            }else if (s.equals("em_")){
                if (jTextField2.getText().length() != 7){
                    ii = 1;
                }
            }else{
                ii = 1;
            }
        }
    }
    
    private void getid() {
        s = jTextField2.getText();
        s = s.substring(0, 3);
    }
}