/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Recordings;


import javax.swing.GroupLayout;

/**
 *
 * @author Arjuna
 */
public class Rec_main extends javax.swing.JPanel {

    /**
     * Creates new form rec_main
     */
    public Rec_main() {
        initComponents();
        loadpanel();
    }
    void loadpanel(){
        jToggleButton1.setSelected(true);
         jPanel1.removeAll();
        GroupLayout gl2=new GroupLayout(jPanel1);

        jPanel1.setLayout(gl2);
        Rec_customer_register rec_customer = new Rec_customer_register();
        gl2.setHorizontalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rec_customer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl2.setVerticalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rec_customer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(1180, 570));
        setMinimumSize(new java.awt.Dimension(1180, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(jToggleButton2);
        jToggleButton2.setText("Customer informations");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 50));

        buttonGroup3.add(jToggleButton1);
        jToggleButton1.setText("New Recording");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, 50));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 990, 530));

        buttonGroup3.add(jToggleButton3);
        jToggleButton3.setText("Recording informations");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        //customer
        
         jPanel1.removeAll();
        GroupLayout gl2=new GroupLayout(jPanel1);

        jPanel1.setLayout(gl2);
        Rec_customer_register rec_customer = new Rec_customer_register();
        gl2.setHorizontalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rec_customer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
        gl2.setVerticalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rec_customer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        jPanel1.removeAll();
        GroupLayout gl2=new GroupLayout(jPanel1);
        jPanel1.setLayout(gl2);
        Rec_customer_details rcd = new Rec_customer_details();
        gl2.setHorizontalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rcd, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        gl2.setVerticalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( rcd, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

        jPanel1.removeAll();
        GroupLayout gl2=new GroupLayout(jPanel1);
        jPanel1.setLayout(gl2);
        Rec_info ri = new Rec_info();
        gl2.setHorizontalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( ri, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        gl2.setVerticalGroup(gl2.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent( ri, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
