/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import CLS.DB;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.tabbedui.RootPanel;

/**
 *
 * @author Arjuna
 */
public class Employee_details extends javax.swing.JPanel {
    private Component RootPanel;

    /**
     * Creates new form employee_details
     */
    
    int i = 0;
    
    public Employee_details() {
        initComponents();
        i = 1;
    }
    
    public static String emid = "";
    String id = "";
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1030, 550));
        setMinimumSize(new java.awt.Dimension(1030, 550));
        setPreferredSize(new java.awt.Dimension(1030, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(1030, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 550));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jPanel1VetoableChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg no", "Name", "Gender", "NIC", "Mobile", "Working Description", "Registration Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTable1VetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 960, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203781_meanicons_24.png"))); // NOI18N
        jButton9.setText("Dismiss");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406204471_user_male.png"))); // NOI18N
        jButton4.setText("View Dismiss Employees");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 210, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203726_editor_list_view_hambuger_menu.png"))); // NOI18N
        jButton5.setText("View all details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 520, 50));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employees Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content bar.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name Or Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 190, -1));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 20));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Search By Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203630_672408-search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        ResultSet rs = null;
        if (jButton4.getText().equals("View Dismiss Employees")){
            try {
                rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Remove"+"'");
                if (!rs.next()){
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(RootPanel, "There Are No Dismissed Employees", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Remove"+"'");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            jButton4.setText("View Current Employees");
            jButton9.setText("Undo Dismiss");
            jTextField1.requestFocus();
        }else{
            try {
                jButton4.setText("View Dismiss Employees");
                jButton9.setText("Dismiss");
                rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Not_Remove"+"'");
                if (!rs.next()){
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    dtm.setRowCount(0);
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(RootPanel, "<html><center>There Are No Registered Employees<br>Please Register Employees And</br> <br>Try Again</br></center></html>", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Not_Remove"+"'");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            jButton4.setText("View Dismiss Employees");
            jButton9.setText("Dismiss");
            jTextField1.requestFocus();
        }
        
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
                while (rs.next()){
                    Vector v = new Vector();
                    v.add(rs.getString("reg_no"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("gender"));
                    v.add(rs.getString("nic"));
                    v.add(rs.getString("mobile"));
                    v.add(rs.getString("working_description"));
                    v.add(rs.getString("registration_date"));
                    dtm.addRow(v);
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        ResultSet rs = null;
        
        if(jTable1.isColumnSelected(jTable1.getSelectedColumn())){
            if (jTable1.isRowSelected(jTable1.getSelectedRow())){
                if (jButton9.getText().equals("Dismiss")){
                String s = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                try {
                    DB.getCon().createStatement().executeUpdate("UPDATE employee SET state = '"+"Remove"+"' WHERE reg_no = '"+s+"'");
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Not_Remove"+"'");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }else{
                String s = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                try {
                    DB.getCon().createStatement().executeUpdate("UPDATE employee SET state = '"+"Not_Remove"+"' WHERE reg_no = '"+s+"'");
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Remove"+"'");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
                try {
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    dtm.setRowCount(0);
                    while (rs.next()){
                        Vector v = new Vector();
                        v.add(rs.getString("reg_no"));
                        v.add(rs.getString("name"));
                        v.add(rs.getString("gender"));
                        v.add(rs.getString("nic"));
                        v.add(rs.getString("mobile"));
                        v.add(rs.getString("working_description"));
                        v.add(rs.getString("registration_date"));
                        dtm.addRow(v);
            }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int raw = jTable1.getSelectedRowCount();
        if (raw == 1){
            emid = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            Employee_detailss ed = new Employee_detailss();
            ed.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int ii = 0;
        if ((jDateChooser1.getDate() == null) &(jDateChooser2.getDate() != null)){
            ii = 1;
        }else if ((jDateChooser1.getDate() != null) &(jDateChooser2.getDate() == null)){
            ii = 1;
        }
        if (ii == 1){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Please Select Next Date");
        }else{
            try {
            id = jTextField1.getText();
            ResultSet rs = null;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            if (jTextField1.getText().equals("") & jDateChooser1.getDate() != null & jDateChooser2.getDate() != null){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date d = jDateChooser1.getDate();
                String date1 = sdf.format(d);
                d = jDateChooser2.getDate();
                String date2 = sdf.format(d);
                rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"'");
            }else if ((!jTextField1.getText().equals("")) & jDateChooser1.getDate() != null & jDateChooser2.getDate() != null){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date d = jDateChooser1.getDate();
                String date1 = sdf.format(d);
                d = jDateChooser2.getDate();
                String date2 = sdf.format(d);
                if (jTextField1.getText().length() >= 3){
                    String s = id.substring(0, 3);
                        if (s.equals("em_")){
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND reg_no LIKE '"+jTextField1.getText()+"%'");
                        }else{
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND name LIKE '%"+jTextField1.getText()+"%'");
                        }
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND name LIKE '%"+jTextField1.getText()+"%'");
                }
            }else if ((!jTextField1.getText().equals("")) & jDateChooser1.getDate() == null & jDateChooser2.getDate() == null){
                if (jTextField1.getText().length() >= 3){
                    String s = id.substring(0, 3);
                        if (s.equals("em_")){
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE reg_no LIKE '"+jTextField1.getText()+"%'");
                        }else{
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE name LIKE '%"+jTextField1.getText()+"%'");
                        }
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE name LIKE '%"+jTextField1.getText()+"%'");
                }
            }
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("reg_no"));
                v.add(rs.getString("name"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("mobile"));
                v.add(rs.getString("working_description"));
                v.add(rs.getString("registration_date"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (jTextField1.getText().isEmpty() & jDateChooser1.getDate() == null & jDateChooser2.getDate() == null){
            load_table();
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
        int ii = 0;
        if ((jDateChooser1.getDate() == null) &(jDateChooser2.getDate() != null)){
            ii = 1;
        }else if ((jDateChooser1.getDate() != null) &(jDateChooser2.getDate() == null)){
            ii = 1;
        }
        if (ii == 1){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Please Select Next Date");
        }else{
            try {
            id = jTextField1.getText();
            ResultSet rs = null;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            if (jTextField1.getText().equals("") & jDateChooser1.getDate() != null & jDateChooser2.getDate() != null){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date d = jDateChooser1.getDate();
                String date1 = sdf.format(d);
                d = jDateChooser2.getDate();
                String date2 = sdf.format(d);
                rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"'");
            }else if ((!jTextField1.getText().equals("")) & jDateChooser1.getDate() != null & jDateChooser2.getDate() != null){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date d = jDateChooser1.getDate();
                String date1 = sdf.format(d);
                d = jDateChooser2.getDate();
                String date2 = sdf.format(d);
                if (jTextField1.getText().length() >= 3){
                    String s = id.substring(0, 3);
                        if (s.equals("em_")){
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND reg_no LIKE '"+jTextField1.getText()+"%'");
                        }else{
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND name LIKE '%"+jTextField1.getText()+"%'");
                        }
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE registration_date BETWEEN '"+date1+"' AND '"+date2+"' AND name LIKE '%"+jTextField1.getText()+"%'");
                }
            }else if ((!jTextField1.getText().equals("")) & jDateChooser1.getDate() == null & jDateChooser2.getDate() == null){
                if (jTextField1.getText().length() >= 3){
                    String s = id.substring(0, 3);
                        if (s.equals("em_")){
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE reg_no LIKE '"+jTextField1.getText()+"%'");
                        }else{
                            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE name LIKE '%"+jTextField1.getText()+"%'");
                        }
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE name LIKE '%"+jTextField1.getText()+"%'");
                }
            }
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("reg_no"));
                v.add(rs.getString("name"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("mobile"));
                v.add(rs.getString("working_description"));
                v.add(rs.getString("registration_date"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (jTextField1.getText().isEmpty() & jDateChooser1.getDate() == null & jDateChooser2.getDate() == null){
            load_table();
        }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown

        
    }//GEN-LAST:event_jTable1ComponentShown

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

        jTextField1.requestFocus();
        jDateChooser2.setEnabled(false);
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained

        if (i == 1){
            load_table();
            i = 2;
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange

        
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTable1VetoableChange

    }//GEN-LAST:event_jTable1VetoableChange

    private void jPanel1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jPanel1VetoableChange

    }//GEN-LAST:event_jPanel1VetoableChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() == 2){
            int raw = jTable1.getSelectedRowCount();
            if (raw == 1){
                emid = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                Employee_detailss ed = new Employee_detailss();
                ed.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange

        jDateChooser2.setMinSelectableDate(jDateChooser1.getDate());
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        jDateChooser2.setEnabled(true);
    }//GEN-LAST:event_jDateChooser1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void load_table() {

        ResultSet rs = null;
        try {
            rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Not_Remove"+"'");
                if (!rs.next()){
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(RootPanel, "<html><center>There Are No Registered Employees<br>Please Register Employees And</br> <br>Try Again</br></center></html>", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    rs = DB.getCon().createStatement().executeQuery("SELECT * FROM employee WHERE state = '"+"Not_Remove"+"'");
                }
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                while (rs.next()){
                    Vector v = new Vector();
                    v.add(rs.getString("reg_no"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("gender"));
                    v.add(rs.getString("nic"));
                    v.add(rs.getString("mobile"));
                    v.add(rs.getString("working_description"));
                    v.add(rs.getString("registration_date"));
                    dtm.addRow(v);
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
