/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Settings;


import CLS.DB;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Arjuna
 */
public class Change_password extends javax.swing.JPanel {
    private Component RootPane;

    /**
     * Creates new form createAccount
     */
    public Change_password() {
        initComponents();
        loadcombo();
        if (jComboBox1.getItemCount() == 0){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPane, "Pelase Create Account", "Information", JOptionPane.INFORMATION_MESSAGE);
            Account_settings.jPanel3.removeAll();
            GroupLayout gl = new GroupLayout(Account_settings.jPanel3);
            Account_settings.jPanel3.setLayout(gl);
            CreateAccount ca = new CreateAccount();
            gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(ca,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE));
            gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(ca,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE));
            Account_settings.jToggleButton1.setSelected(true);
            Account_settings.jToggleButton2.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(163, 163, 163));
        setMaximumSize(new java.awt.Dimension(427, 252));
        setMinimumSize(new java.awt.Dimension(427, 252));
        setPreferredSize(new java.awt.Dimension(427, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseEntered(evt);
            }
        });
        jLayeredPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLayeredPane1PropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User Name");
        jLabel1.setBounds(40, 7, 140, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Confirm Password");
        jLabel3.setBounds(40, 127, 140, 30);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("New password");
        jLabel2.setBounds(40, 87, 130, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203462_black_2_audio_simple_repeat_2.png"))); // NOI18N
        jButton1.setText("Change password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        jButton1.setBounds(130, 170, 160, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Current password");
        jLabel4.setBounds(40, 50, 140, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setBounds(180, 10, 160, 30);
        jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.setBounds(180, 50, 160, 30);
        jLayeredPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.setBounds(180, 90, 160, 30);
        jLayeredPane1.add(jPasswordField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPasswordField3.setBounds(180, 130, 160, 30);
        jLayeredPane1.add(jPasswordField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 388, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseEntered

    }//GEN-LAST:event_jLayeredPane1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int i = 0;
        String p1 = new String(jPasswordField1.getPassword());
        String p2 = new String(jPasswordField2.getPassword());
        String p3 = new String(jPasswordField3.getPassword());
        if (p1.isEmpty()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPane, "Please Enter The Current Password", "Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField1.requestFocus();
            i = 1;
        }else if (p2.isEmpty()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPane, "Please Enter New Password", "Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField2.requestFocus();
            i = 1;
        }else if (p3.isEmpty()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPane, "Please Confirm The Password", "Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField3.requestFocus();
            i = 1;
        }else{
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT password FROM login WHERE username = '"+jComboBox1.getSelectedItem()+"'");
                    while (rs.next()){
                        if (rs.getString("password").equals(p1)){
                            if (p2.equals(p3)){
                                DB.getCon().createStatement().executeUpdate("UPDATE login SET password = '"+p1+"' WHERE username = '"+jComboBox1.getSelectedItem()+"'");
                                Toolkit.getDefaultToolkit().beep();
                                JOptionPane.showMessageDialog(RootPane, "Done", "Create Account", JOptionPane.INFORMATION_MESSAGE);
                                jPasswordField1.setText("");
                                jPasswordField2.setText("");
                                jPasswordField3.setText("");
                                jPasswordField1.requestFocus();
                            }else{
                                Toolkit.getDefaultToolkit().beep();
                                JOptionPane.showMessageDialog(RootPane, "Password Doesn't Match", "Error", JOptionPane.ERROR_MESSAGE);
                                jPasswordField2.setText("");
                                jPasswordField3.setText("");
                                jPasswordField2.requestFocus();
                            }
                        }else{
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(RootPane, "Password Is Incorrect", "Error", JOptionPane.ERROR_MESSAGE);
                            jPasswordField1.setText("");
                            jPasswordField1.requestFocus();
                        }
                    }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

        jPasswordField2.requestFocus();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed

        jPasswordField3.requestFocus();
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed

        jButton1.requestFocus();
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jLayeredPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLayeredPane1PropertyChange

        jPasswordField1.requestFocus();
    }//GEN-LAST:event_jLayeredPane1PropertyChange

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange

    }//GEN-LAST:event_jButton1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables

    private void loadcombo() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT username FROM login");
            jComboBox1.removeAllItems();
            while (rs.next()){
                jComboBox1.addItem(rs.getString("username"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
