/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Settings;


import CLS.DB;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arjuna
 */
public class Delete_account extends javax.swing.JPanel {
    private Component RootPane;

    /**
     * Creates new form createAccount
     */
    public Delete_account() {
        initComponents();
        loadtable();
        if (jTable1.getRowCount() == 0){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPane, "Pelase Create Account", "Information", JOptionPane.INFORMATION_MESSAGE);
            Account_settings.jPanel3.removeAll();
            GroupLayout gl = new GroupLayout(Account_settings.jPanel3);
            Account_settings.jPanel3.setLayout(gl);
            CreateAccount ca = new CreateAccount();
            gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(ca,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE));
            gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(ca,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE));
            Account_settings.jToggleButton1.setSelected(true);
            Account_settings.jToggleButton3.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 163, 163));
        setMaximumSize(new java.awt.Dimension(427, 252));
        setMinimumSize(new java.awt.Dimension(427, 252));
        setPreferredSize(new java.awt.Dimension(427, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseEntered(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(20, 20, 350, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean small.png"))); // NOI18N
        jButton1.setText("Delete Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(120, 160, 160, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 388, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseEntered

    }//GEN-LAST:event_jLayeredPane1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTable1.isRowSelected(jTable1.getSelectedRow())){
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            String s = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            Toolkit.getDefaultToolkit().beep();
            int ii = JOptionPane.showConfirmDialog(RootPane, "Are You Sure ?", "Delete Account", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (ii == 0){
                try {
                    DB.getCon().createStatement().executeUpdate("DELETE FROM login WHERE username = '"+s+"'");
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(RootPane, "Done", "Delete Account", JOptionPane.INFORMATION_MESSAGE);
                    loadtable();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadtable() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT username FROM login");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("username"));
                v.add("********");
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }

}
