/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import CLS.DB;
import Main_Menu.Event_calender;
import Main_Menu.Main_menu;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ashan
 */
public class Deal_event_register extends javax.swing.JPanel {

    /**
     * Creates new form deal_event_register1
     */
    public static String ev_id = "";
    public static String cu_id = "";
    public static int sd1 = 0;
    public static int sd2 = 0;
    public static int dd = 0;
    Border brr = null;
    Border brr2 = null;
    Border brr3 = null;
    Border brr4 = null;
    private Component RootPanel;

    public Deal_event_register() {
        initComponents();
        autogen();
        if (Event_calender.ddd != null) {
            jDateChooser1.setDate(Event_calender.ddd);
        }
        Event_calender.ddd = null;
        jRadioButton1.setSelected(true);
        jLabel4.setVisible(false);
        jDateChooser2.setVisible(false);
        jLabel1.setText(Deal_customer_register.deal_cus_id);
        if (!(ev_id.isEmpty())) {
            jTextField1.setText(ev_id);
            autofill();
        }
        if (!(Event_manager_1.sss.isEmpty())) {
            jTextField1.setText(Event_manager_1.sss);
            autofill();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1030, 550));
        setMinimumSize(new java.awt.Dimension(1030, 550));
        setPreferredSize(new java.awt.Dimension(1030, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(1030, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 550));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Description :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Event Register");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Event date");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 490, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 490, -1));

        jLabel15.setText("Street :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1406203781_meanicons_24.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 100, 30));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 490, -1));

        jLabel10.setText("From :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Address :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 490, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Days :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        jLabel19.setText("City :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 430, 110));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Time :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Event ID :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Customer Requirment :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 170, -1));

        jLabel13.setText("No :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel11.setText("To :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("More Days");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Location Contact :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content bar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 140, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 140, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Customer ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer id ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 5, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 240, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arrow-Next-icon.png"))); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 100, 30));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Location Name :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("One Day");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Event name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel4.setText("To");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arrow-Back-icon.png"))); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 100, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox2FocusGained(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, -1));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jTextField2.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

        jDateChooser1.requestFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MousePressed
    }//GEN-LAST:event_jDateChooser1MousePressed

    private void jDateChooser1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseReleased
    }//GEN-LAST:event_jDateChooser1MouseReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

        jTextField6.requestFocus();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed

        jTextField7.requestFocus();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed

        jTextField8.requestFocus();
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed

        jTextField9.requestFocus();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed

        jTextField10.requestFocus();
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int iii = 0;
        Border br = new LineBorder(Color.red);
        if (jRadioButton1.isSelected()) {
            if ((jDateChooser1.getDate() == null)) {
                jDateChooser1.setBorder(br);
                iii = 1;
            }
        } else {
            if ((jDateChooser1.getDate() == null)) {
                jDateChooser1.setBorder(br);
                iii = 1;
            }
            if ((jDateChooser2.getDate() == null)) {
                jDateChooser2.setBorder(br);
                iii = 1;
            }
        }
        if (jTextField2.getText().isEmpty()) {
            jTextField2.setBorder(br);
            iii = 1;
        }
        if (jTextField5.getText().isEmpty()) {
            jTextField5.setBorder(br);
            iii = 1;
        }
        if (jTextField6.getText().isEmpty()) {
            jTextField6.setBorder(br);
            iii = 1;
        }
        if (jTextField7.getText().isEmpty()) {
            jTextField7.setBorder(br);
            iii = 1;
        }
        if (jTextField8.getText().isEmpty()) {
            jTextField8.setBorder(br);
            iii = 1;
        }
        if (jTextField9.getText().isEmpty()) {
            jTextField9.setBorder(br);
            iii = 1;
        }
        if (jTextField10.getText().isEmpty()) {
            jTextField10.setBorder(br);
            iii = 1;
        }
        if (jTextArea1.getText().isEmpty()) {
            jTextArea1.setBorder(br);
            iii = 1;
        }
        if (jComboBox2.getSelectedItem() == "00:00") {
            jComboBox2.setBorder(br);
            iii = 1;
        }

        if (iii == 1) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(RootPanel, "Complete These Textboxes", "Error", JOptionPane.ERROR_MESSAGE);
            jTextField2.requestFocus();
        } else {
            Date d = new Date();
            Date d1 = jDateChooser1.getDate();
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
            String dd5 = sdf2.format(d);
            String dd6 = sdf2.format(d1);
            if (jRadioButton2.isSelected()) {
                Date dd2 = jDateChooser2.getDate();
                String dd7 = sdf2.format(dd2);
                if (dd7.compareTo(dd6) < 0) {
                    jDateChooser2.setBorder(br);
                    iii = 1;
                } else if (dd7.equals(dd6)) {
                    jDateChooser2.setBorder(br);
                    iii = 1;
                }
            }
            if ((dd6.compareTo(dd5) < 0)) {
                jDateChooser1.setBorder(br);
                iii = 1;
            }
            int ii = 0;
            int t1 = jComboBox1.getSelectedIndex();
            int t2 = jComboBox2.getSelectedIndex();
            if (t1 == t2) {
                ii = 1;
            } else if (t1 > t2) {
                ii = 1;
            }
            int ij = 0;
            if (ii == 1) {
                jComboBox2.setBorder(br);
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(RootPanel, "Can Not Select This Time");
                jComboBox2.requestFocus();
                ij = 1;
            }
            if (iii == 1) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(RootPanel, "Icorrect Date");
                jDateChooser1.requestFocus();
                ij = 1;
            }
            if (ij != 1) {
                int ie = 0;
                ev_id = jTextField1.getText();
                cu_id = jLabel1.getText();
                String days = "";
                d = jDateChooser1.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String df = sdf.format(d);
                try {
                    ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT event_id,name FROM event_details WHERE event_date_from = '" + df + "'");
                    if (rs.first()) {
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_id,name FROM event_details WHERE event_date_from = '" +df+ "' AND event_id != '"+jTextField1.getText()+"'");
                        while (rs.next()) {
                            String s1 = rs.getString("event_id");
                            String s2 = rs.getString("name");
                            Toolkit.getDefaultToolkit().beep();
                            ie = JOptionPane.showConfirmDialog(RootPanel, "<html><center>There Is A Same Date Event<br></br><br>Event ID = <b><font color = 'green'> " + s1 + " </font></b>  &  Event Name = <b><font color = 'blue'> " + s2 + " </font></b></br><br></br><br>Are You Want Save This Event ?</br></center></html>", "Information", JOptionPane.YES_NO_OPTION);
                            jDateChooser1.requestFocus();
                        }
                    } else {
                        ie = 0;
                    }
                    if (ie == 0) {
                        Date ddd = new Date();
                        SimpleDateFormat sdf11 = new SimpleDateFormat("yyyy-MM-dd");
                        SimpleDateFormat sdf22 = new SimpleDateFormat("HH:mm:ss");
                        String s11 = sdf11.format(ddd);
                        String s22 = sdf22.format(ddd);
                        String c_name = "";
                        rs = DB.getCon().createStatement().executeQuery("SELECT name FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                        while (rs.next()){
                            c_name = rs.getString("name");
                        }
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_id FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                        if (!rs.next()) {
                            if (jRadioButton1.isSelected()) {
                                dd = 1;
                                days = "single";
                                DB.getCon().createStatement().executeUpdate("INSERT INTO event_details (event_id,event_customer_details_reg_no,customer_name,name,days,event_date_from,time_from,time_to,location,no,street,city,contact,description,customer_requirement,state,date,time,user) VALUES ('" + jTextField1.getText() + "','" + jLabel1.getText() + "','"+ c_name +"','" + jTextField2.getText() + "','" + days + "','" + df + "','" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jTextField5.getText() + "','" + jTextField6.getText() + "','" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextArea1.getText() + "','" + "Not_Remove" + "','"+ s11 +"','"+ s22 +"','"+ Login.User_login.user +"')");
                            } else {
                                dd = 2;
                                d = jDateChooser2.getDate();
                                String dt = sdf.format(d);
                                days = "More";
                                DB.getCon().createStatement().executeUpdate("INSERT INTO event_details (event_id,event_customer_details_reg_no,customer_name,name,days,event_date_from,event_date_to,time_from,time_to,location,no,street,city,contact,description,customer_requirement,state,date,time,user) VALUES ('" + jTextField1.getText() + "','" + jLabel1.getText() + "','"+ c_name +"','" + jTextField2.getText() + "','" + days + "','" + df + "','" + dt + "','" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jTextField5.getText() + "','" + jTextField6.getText() + "','" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextArea1.getText() + "','" + "Not_Remove" + "','"+ s11 +"','"+ s22 +"','"+ Login.User_login.user +"')");
                            }
                        } else {
                            if (jRadioButton1.isSelected()) {
                                dd = 1;
                                days = "single";
                                DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', customer_name = '"+ c_name +"', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_from = '" + df + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "', date = '"+ s11 +"', time = '"+ s22 +"', user = '"+ Login.User_login.user +"' WHERE event_id = '" + jTextField1.getText() + "'");
                            } else {
                                dd = 2;
                                d = jDateChooser2.getDate();
                                String dt = sdf.format(d);
                                days = "More";
                                DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', customer_name = '"+ c_name +"', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_from = '" + df + "', event_date_to = '" + dt + "',time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "', date = '"+ s11 +"', time = '"+ s22 +"', user = '"+ Login.User_login.user +"' WHERE event_id = '" + jTextField1.getText() + "'");
                            }
                        }
                        sd2 = 1;
                        jPanel1.removeAll();
                        GroupLayout layout = new GroupLayout(jPanel1);
                        jPanel1.setLayout(layout);
                        Event_manager_1 em = new Event_manager_1();
                        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(em, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(em, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jTextField2.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jLabel4.setVisible(false);
        jDateChooser2.setVisible(false);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextArea1.setText("");
        jTextField2.requestFocus();
        cu_id = "";
        ev_id = "";
        dd = 0;
        Event_manager_1.sss = "";
        Deal_customer_register.deal_cus_id = "";
        Deal_customer_register.evv_id = "";
        autogen();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Toolkit.getDefaultToolkit().beep();
        int i = JOptionPane.showConfirmDialog(RootPanel, "Are You Sure ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT event_id FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                if (rs.first()) {
                    rs = DB.getCon().createStatement().executeQuery("SELECT event_manager_id FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                    if (rs.first()) {
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_customer_details_reg_no = '" + jLabel1.getText() + "' AND event_id != '" + jTextField1.getText() + "'");
                        if (!(rs.first())) {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_component WHERE event_manager_component_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_package WHERE idevent_manager_package_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                        } else {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_component WHERE event_manager_component_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_package WHERE idevent_manager_package_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                        }
                    } else {
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_customer_details_reg_no = '" + jLabel1.getText() + "' AND event_id != '" + jTextField1.getText() + "'");
                        if (!(rs.first())) {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                        } else {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                        }
                    }
                } else {
                    rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_id != '" + jTextField1.getText() + "'");
                    if (!(rs.first())) {
                        DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            jTextField2.setText("");
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
            jLabel4.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextArea1.setText("");
            jTextField2.requestFocus();
            cu_id = "";
            ev_id = "";
            dd = 0;
            Event_manager_1.sss = "";
            Deal_customer_register.deal_cus_id = "";
            Deal_customer_register.evv_id = "";
            Main_menu.jPanel1.removeAll();
            GroupLayout gl = new GroupLayout(Main_menu.jPanel1);
            Main_menu.jPanel1.setLayout(gl);
            Event_calender evc = new Event_calender();
            gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(evc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(evc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        jLabel4.setVisible(true);
        jDateChooser2.setVisible(true);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jLabel4.setVisible(false);
        jDateChooser2.setVisible(false);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Deal_customer_register.evv_id = jTextField1.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String days = "";
        if (jRadioButton1.isSelected()) {
            days = "single";
        } else {
            days = "More";
        }
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT event_id FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
            if (!(rs.next())) {
                DB.getCon().createStatement().executeUpdate("INSERT INTO event_details (event_id,event_customer_details_reg_no,days,state) VALUES ('" + jTextField1.getText() + "','" + jLabel1.getText() + "', '" + days + "', '" + "Not_Remove" + "')");
            }
            if (jRadioButton1.isSelected()) {
                System.out.println("1");
                dd = 1;
                if (jDateChooser1.getDate() == null) {
                    System.out.println("2");
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                        System.out.println("3");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    Date d = jDateChooser1.getDate();
                    String df = sdf.format(d);
                    days = "single";
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_from = '" + df + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

            } else {
                days = "More";
                dd = 2;
                if (jDateChooser1.getDate() == null & jDateChooser2.getDate() == null) {
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else if ((!(jDateChooser1.getDate() == null)) & jDateChooser2.getDate() == null) {
                    Date d = jDateChooser1.getDate();
                    String df = sdf.format(d);
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_from = '" + df + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else if (jDateChooser1.getDate() == null & (!(jDateChooser2.getDate() == null))) {
                    Date d = jDateChooser2.getDate();
                    String dt = sdf.format(d);
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_to = '" + dt + "', time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    Date d = jDateChooser1.getDate();
                    String df = sdf.format(d);
                    d = jDateChooser2.getDate();
                    String dt = sdf.format(d);
                    try {
                        DB.getCon().createStatement().executeUpdate("UPDATE event_details SET event_customer_details_reg_no = '" + jLabel1.getText() + "', name = '" + jTextField2.getText() + "', days = '" + days + "', event_date_from = '" + df + "', event_date_to = '" + dt + "',time_from = '" + jComboBox1.getSelectedItem().toString() + "', time_to = '" + jComboBox2.getSelectedItem().toString() + "', location = '" + jTextField5.getText() + "', no = '" + jTextField6.getText() + "', street = '" + jTextField7.getText() + "', city = '" + jTextField8.getText() + "', contact = '" + jTextField9.getText() + "', description = '" + jTextField10.getText() + "', customer_requirement = '" + jTextArea1.getText() + "' WHERE event_id = '" + jTextField1.getText() + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        sd2 = 1;
        cu_id = jLabel1.getText();
        jPanel1.removeAll();
        GroupLayout layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(layout);
        Deal_customer_register strr1 = new Deal_customer_register();
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(strr1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(strr1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed

        jTextArea1.requestFocus();
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

        sd1+=1;
        if (sd1 == 2){
            if (sd2 != 1){
                cancel();
            }
            sd1 = 0;
            sd2 = 0;
        }
        brr = jTextField2.getBorder();
        brr2 = jDateChooser1.getBorder();
        brr3 = jTextArea1.getBorder();
        brr4 = jComboBox2.getBorder();
        jTextField2.requestFocus();
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained

        jTextField2.setBorder(brr);
        jDateChooser1.setBorder(brr2);
        jDateChooser2.setBorder(brr2);
        jTextField5.setBorder(brr);
        jTextField6.setBorder(brr);
        jTextField7.setBorder(brr);
        jTextField8.setBorder(brr);
        jTextField9.setBorder(brr);
        jTextField10.setBorder(brr);
        jTextArea1.setBorder(brr3);
        jComboBox2.setBorder(brr4);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jDateChooser2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser2FocusGained

        jDateChooser2.setBorder(brr2);
    }//GEN-LAST:event_jDateChooser2FocusGained

    private void jDateChooser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser1FocusGained

        jDateChooser1.setBorder(brr2);
        jDateChooser2.setBorder(brr2);
    }//GEN-LAST:event_jDateChooser1FocusGained

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusGained

        jComboBox1.setBorder(brr4);
        jComboBox2.setBorder(brr4);
    }//GEN-LAST:event_jComboBox2FocusGained

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained

        jComboBox1.setBorder(brr4);
        jComboBox2.setBorder(brr4);
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        Date d = new Date();
        jDateChooser1.setMinSelectableDate(d);
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange

        jDateChooser2.setMinSelectableDate(jDateChooser1.getDate());
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped

        int i = evt.getKeyChar();
        char c = evt.getKeyChar();
        if (!(c>= '0' & c<= '9')){
            if (i == 43){
            }else if (i == 45){
            }else{
                evt.consume();
            }
            if (i == 8){
            }else if (i == 10) {
            }else if (i == 43){
            }else if (i == 45){
            }else{
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void autogen() {
        jLabel1.setText(Deal_customer_register.deal_cus_id);
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM event_details");
            if (!rs.next()) {
                jTextField1.setText("ev_000001");
            } else {
                rs = DB.getCon().createStatement().executeQuery("SELECT MAX(event_id) FROM event_details");
                while (rs.next()) {
                    String s = rs.getString("MAX(event_id)");
                    int i = Integer.parseInt(s.substring(3, 9));
                    i += 1;
                    NumberFormat formatter = new DecimalFormat("000000");
                    jTextField1.setText("ev_" + formatter.format(i));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void autofill() {
        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT * FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
            while (rs.next()) {
                if (rs.getString("days").equals("single")) {
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                    jLabel4.setVisible(false);
                    jDateChooser2.setVisible(false);
                    jTextField2.setText(rs.getString("name"));
                    jDateChooser1.setDate(rs.getDate("event_date_from"));
                    jComboBox1.setSelectedItem(rs.getString("time_from"));
                    jComboBox2.setSelectedItem(rs.getString("time_to"));
                    jTextField5.setText(rs.getString("location"));
                    jTextField6.setText(rs.getString("no"));
                    jTextField7.setText(rs.getString("street"));
                    jTextField8.setText(rs.getString("city"));
                    jTextField9.setText(rs.getString("contact"));
                    jTextField10.setText(rs.getString("description"));
                    jTextArea1.setText(rs.getString("customer_requirement"));
                } else {
                    jRadioButton2.setSelected(true);
                    jRadioButton1.setSelected(false);
                    jLabel4.setVisible(true);
                    jDateChooser2.setVisible(true);
                    jTextField2.setText(rs.getString("name"));
                    jDateChooser1.setDate(rs.getDate("event_date_from"));
                    jDateChooser2.setDate(rs.getDate("event_date_to"));
                    jComboBox1.setSelectedItem(rs.getString("time_from"));
                    jComboBox2.setSelectedItem(rs.getString("time_to"));
                    jTextField5.setText(rs.getString("location"));
                    jTextField6.setText(rs.getString("no"));
                    jTextField7.setText(rs.getString("street"));
                    jTextField8.setText(rs.getString("city"));
                    jTextField9.setText(rs.getString("contact"));
                    jTextField10.setText(rs.getString("description"));
                    jTextArea1.setText(rs.getString("customer_requirement"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void cancel() {
        try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT event_id FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                if (rs.first()) {
                    rs = DB.getCon().createStatement().executeQuery("SELECT event_manager_id FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                    if (rs.first()) {
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_customer_details_reg_no = '" + jLabel1.getText() + "' AND event_id != '" + jTextField1.getText() + "'");
                        if (!(rs.first())) {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_component WHERE event_manager_component_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_package WHERE idevent_manager_package_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                        } else {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_component WHERE event_manager_component_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager_package WHERE idevent_manager_package_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_manager WHERE event_manager_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                        }
                    } else {
                        rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_customer_details_reg_no = '" + jLabel1.getText() + "' AND event_id != '" + jTextField1.getText() + "'");
                        if (!(rs.first())) {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                        } else {
                            DB.getCon().createStatement().executeUpdate("DELETE FROM event_details WHERE event_id = '" + jTextField1.getText() + "'");
                        }
                    }
                } else {
                    rs = DB.getCon().createStatement().executeQuery("SELECT event_customer_details_reg_no FROM event_details WHERE event_id != '" + jTextField1.getText() + "'");
                    if (!(rs.first())) {
                        DB.getCon().createStatement().executeUpdate("DELETE FROM event_customer_details WHERE reg_no = '" + jLabel1.getText() + "'");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            jTextField2.setText("");
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
            jLabel4.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextArea1.setText("");
            jTextField2.requestFocus();
            cu_id = "";
            ev_id = "";
            dd = 0;
            Event_manager_1.sss = "";
            Deal_customer_register.deal_cus_id = "";
            Deal_customer_register.evv_id = "";
    }
}
